#%RAML 1.0 DataType
description: datatype that represents a collection of CDM/Project Response and its relevant attributes

properties:
  projects:
    type: array
    items: !include ../exchange_modules/a6a6fe5a-a2c2-46ac-aa31-c390a0ddaa1d/cdm-library/2.2.30/types/project.raml