#%RAML 1.0 NamedExample

units:
  - productId: "p001"
    phProductId: "phP001" 
    caStockId: "caS001"
    projectId: "pr001" 
    phProjectId: "phPr001"       
    status: "Pipeline"
    type: "Residential"
    propertyType: "Alpine"
    headline: "test"  
    description: ""  
    address:    
      postcode: "" 
      state: "" 
      unitNumber: "" 
      longitude: "" 
      suburb: "Sydney" 
      streetName: "King Street" 
      streetNumber: "" 
      country: "Australia" 
      latitude: ""
    displayAddress: true
    price: 1234
    priceLimit: 1000
    priceText: ""
    displayPrice: "None"
    soldDate: "2015-07-04T21:00:00"
    dateAvailable: 2020-07-24
    underOffer: false
    pricePeriod: "Weekly"
    bondDeposit: 1
    soldPrice: 1234
    showSoldPrice: true
    firstAgentId: 12334
    builtYear: "1990"
    carportSpaces: 8
    garageSpaces: 1
    offStreetSpaces: 1
    bedrooms: 2
    halfBedroom: false
    bathrooms: 1
    halfBathroom: false
    ensuites: 0
    landArea: 0
    landAreaMetric: "Square Yards"
    floorArea: 0
    floorAreaMetric: "Square Metres"
    landFrontage: 0
    landFrontageMetric: "0"
    energyEfficiencyRating: "0"
    entranceFloor: "0"
    productCode: "PCODE"
    numberOfFloors: 2
    newConstruction: false
    propertyUrl: "http://google.com"
    virtualTourUrl: "http://google.com"
    extLink1: ""
    extLink2: ""
    videoUrl: ""
    auctionPlace: ""
    auctionDate: 2020-07-23
    auctionTime: ""
    forthcomingAuction: false
    developmentName: "Test Dev"
    authority: ""
    methodOfSale: ""
    propertyId: "pr001"
    apartmentId: "apt001"
    specials: ""

  - productId: "p001"
    phProductId: "phP001" 
    caStockId: "caS001"
    projectId: "pr001" 
    phProjectId: "phPr001"       
    status: "Pipeline"
    type: "Residential"
    propertyType: "Alpine"
    headline: "test"  
    description: ""  
    address:    
      postcode: "" 
      state: "" 
      unitNumber: "" 
      longitude: "" 
      suburb: "Sydney" 
      streetName: "King Street" 
      streetNumber: "" 
      country: "Australia" 
      latitude: ""
    displayAddress: true
    price: 1234
    priceLimit: 1000
    priceText: ""
    displayPrice: "None"
    soldDate: "2015-07-04T21:00:00"
    dateAvailable: 2020-07-24
    underOffer: false
    pricePeriod: "Weekly"
    bondDeposit: 1
    soldPrice: 1234
    showSoldPrice: true
    firstAgentId: 12345
    builtYear: "1990"
    carportSpaces: 8
    garageSpaces: 1
    offStreetSpaces: 1
    bedrooms: 2
    halfBedroom: false
    bathrooms: 1
    halfBathroom: false
    ensuites: 0
    landArea: 0
    landAreaMetric: "Square Yards"
    floorArea: 0
    floorAreaMetric: "Square Metres"
    landFrontage: 0
    landFrontageMetric: "123"
    energyEfficiencyRating: "0"
    entranceFloor: "0"
    productCode: "PCODE"
    numberOfFloors: 2
    newConstruction: false
    propertyUrl: "http://google.com"
    virtualTourUrl: "http://google.com"
    extLink1: ""
    extLink2: ""
    videoUrl: ""
    auctionPlace: ""
    auctionDate: 2020-07-23
    auctionTime: ""
    forthcomingAuction: false
    developmentName: "Test Dev"
    authority: ""
    methodOfSale: ""
    propertyId: "pr001"
    apartmentId: "apt001"
    specials: ""  