#%RAML 1.0 NamedExample
projects:
  - projectId: "21606"
    phProjectId: ""
    listingClientId" : "12345" 
    name" : "Sydney Harbour Office Test" 
    description" : "This is a test project from MuleSoft API" 
    status" : "Unknows Staus" 
    yearBuild": 5  
    noOfStreetParking": 20 
    energyEfficiencyRating": 0 
    newConstruction": false 
    url": "http://facebook.com/test" 
    showAddress": "Yes" 
    address: 
      postcode: "" 
      state: "" 
      unitNumber: "" 
      longitude: "" 
      suburb: "Sydney" 
      streetName: "King Street" 
      streetNumber: "" 
      country: "Australia" 
      latitude: ""
    vitualTourURL: "http://facebook.com/test" 
    videoURL: "http://facebook.com/test" 
    externalLink1: "http://facebook.com/test" 
    externalLink2: "http://facebook.com/test" 
    upcomingAuction: "Yes" 
    auction:
      auctionDate: "2015-05-23" 
      auctionPlace: "" 
      auctionTime: "12:30:00"
    email: "customer@service.com"
    phone: "02033448555"
    salesAuthority: "For Lease" 
    methodOfSales: "Exclusive" 
    publishTo: "Domain"  
    publishToForAudit: "Yes"  
    listingAgentId: "308762"
    listingLastSyncStatus: ""
    listingLastSyncDateTime: "2015-07-04T21:00:00"
    agents:
      - phAgentId: "phA001"
        phProjectId: "phP001"
        agentType: string
        firstName?: string
        lastName: "agentLastName"
        email: "test@test.com"
        phoneNumber: "1234567889"
        mobileNumber: ""
        faxNumber: "123"
        username: "test User"
        level: ""
        description: ""
        position: ""
        suburb: ""
        role: "" 
        fullName: "agent owner name"
    propertyCode: "p001"
  - projectId: "21607"
    phProjectId: ""
    listingClientId" : "12345" 
    name" : "Sydney Harbour Office Test" 
    description" : "This is a test project from MuleSoft API" 
    status" : "Unknows Staus" 
    yearBuild": 5  
    noOfStreetParking": 20 
    energyEfficiencyRating": 0 
    newConstruction": false 
    url": "http://facebook.com/test" 
    showAddress": "Yes" 
    address: 
      postcode: "" 
      state: "" 
      unitNumber: "" 
      longitude: "" 
      suburb: "Sydney" 
      streetName: "King Street" 
      streetNumber: "" 
      country: "Australia" 
      latitude: ""
    vitualTourURL: "http://facebook.com/test" 
    videoURL: "http://facebook.com/test" 
    externalLink1: "http://facebook.com/test" 
    externalLink2: "http://facebook.com/test" 
    upcomingAuction: "Yes" 
    auction:
      auctionDate: "2015-05-23" 
      auctionPlace: "" 
      auctionTime: "12:30:00"
    email: "customer@service.com"
    phone: "02033448555"
    salesAuthority: "For Lease" 
    methodOfSales: "Exclusive" 
    publishTo: "Domain"  
    publishToForAudit: "Yes"  
    listingAgentId: "308762"
    listingLastSyncStatus: ""
    listingLastSyncDateTime: "2015-07-04T21:00:00"
    agents:
      - phAgentId: "phA002"
        phProjectId: "phP002"
        agentType: string
        firstName?: string
        lastName: "agentLastName"
        email: "test@test.com"
        phoneNumber: "1234567889"
        mobileNumber: ""
        faxNumber: "123"
        username: "test User"
        level: ""
        description: ""
        position: ""
        suburb: ""
        role: "" 
        fullName: "agent owner name"
    propertyCode: "p002"
