#%RAML 1.0 Library
usage: This is the common API fragment which could be referenced and reused by the different API assets. 

traits:
  compliant: !include traits/compliant.raml
  client-id-auth: !include traits/client-id-required.raml
  