https:
  port: "8082"
  host: "0.0.0.0"
  key:
    alias: "lendlease"

anypoint.api.id: "16011340"

salesforce:
  username: "msapi@lendlease.com.uat01"
  token.endpoint: "https://login.salesforce.com/services/oauth2/token"
  api.version: "47.0"
  
  

json.logger.application:
  version: 1.2.0
  name: ll-sys-global-sfdc-uat

globalOrg:
  listings.update.objectName: "PLM_ListingStatus__c"

validation.messages:
  product.id: "Invalid Product"
    