#%RAML 1.0 DataType
description: features of property from marketing colaterals. MarketingCollaterals are having 3 recordTypes (Feature, Media, InspectionTime). PropertyHubId for features are static thus we don't need it here. 

type: string[]