#%RAML 1.0 DataType
description: listing of the property based on PLM_ListingStatus__c custom object.

properties:
  sfId?: string     
  listingSite?: string
  listingStatus?: string
  phId?: string
  lastSent?: datetime-only
  lastConfirmed?: datetime-only
  lastStatus?: string
  productId? : string 
  lastExport? : datetime-only