#%RAML 1.0 NamedExample
  extLeadId: "123123123123123123"
  contact:
    firstName: "First "
    lastName: "Last Name"
    email: "test@test.com"
    phone: "121356345"
    address: 
      streetNumber: "123 Ave"
      streetName: "CA Street"
      unitNumber: ""
      state: "CA"
      country: "" # required in CDM
      suburb: "" # required in CDM
      postcode: "12345"
    extContactId: "321123131231221"
  campaign:
    source: "camp"
  project: 
    propertyCode: "C100"  
  agent:
    agentType: "Unit" # required in CDM
    fullName: "AgentTest"  
  property: 
    productCode: "C100"  
  lease:
    startDate: 2020-07-13
    endDate: 2020-08-13
    tenantType: "Individual"