#%RAML 1.0 DataType
description: MarketingCollaterals are having 3 recordTypes (Feature, Media, InspectionTime), if the recordType is media then is has one of defined media types (Photo, Floorplan, Brochure). 
    
properties:
  photos:
    required: false
    type: array
    items:
      type: !include common/media-item.raml
          
  
  floorplans:
    required: false
    type: array
    items:
      type: !include common/media-item.raml
          
  brochures:
    required: false
    type: array
    items:
      type: !include common/media-item.raml