{
  "headers": {
    "host": "localhost:8083",
    "connection": "keep-alive",
    "cache-control": "no-cache",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
    "postman-token": "a9470130-d420-26b2-19bc-b00c7b19d717",
    "accept": "*/*",
    "sec-fetch-site": "none",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/tenants",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": null,
  "listenerPath": "/api/tenants",
  "localAddress": "/127.0.0.1:8083",
  "relativePath": "/api/tenants",
  "uriParams": {},
  "rawRequestUri": "/api/tenants",
  "rawRequestPath": "/api/tenants",
  "remoteAddress": "/127.0.0.1:53123",
  "requestPath": "/api/tenants"
}