#%RAML 1.0 DataType
description: datatype that represents a Campaign and its relevant attributes

properties:
  source: 
    type: string    
    required: false
    maxLength: 30
    displayName: Source
    description: Primary marketing Source
  