#%RAML 1.0 DataType

properties:
  photos?: 
    type: array 
    items: !include single-media-update.raml
  floorplans?: 
    type: array 
    items: !include single-media-update.raml
  brochures?: 
    type: array 
    items: !include single-media-update.raml