https:
  port: "8082"
  host: "0.0.0.0"
  key:
    alias: "lendlease"

anypoint.api.id: "16274887"

http:
  port: "8081"
  host: "0.0.0.0"
  key:
    alias: "lendlease"
        
json.logger.application:
  version: 1.1.0
  name: ll-sys-yardi-project

rentCafe:    
  username: "BTRLeadsAPI@lendlease.com"
  path: "api.rentcafe.co.uk"
  basePath: "rentcafeapi.aspx"
  port: ""