#%RAML 1.0 Library


types: 
  property: !include types/property.raml
  address: !include types/common/address.raml
  feature: !include types/feature.raml
  inspectionTime: !include types/inspection-time.raml
  listing: !include types/listing.raml
  media: !include types/media.raml
  propertyDetail: !include types/property-details.raml
  project: !include types/project.raml
  office: !include types/office.raml
  agent: !include types/agent.raml
  lead: !include types/lead.raml

  property-op: !include cdm-optional/property-op.raml
  address-op: !include cdm-optional/common/address-op.raml
  feature-op: !include cdm-optional/feature-op.raml
  inspectionTime-op: !include cdm-optional/inspection-time-op.raml
  listing-op: !include cdm-optional/listing-op.raml
  media-op: !include cdm-optional/media-op.raml
  propertyDetail-op: !include cdm-optional/property-details-op.raml
  project-op: !include cdm-optional/project-op.raml
  office-op: !include cdm-optional/office-op.raml
  agent-op: !include cdm-optional/agent-op.raml
  