#%RAML 1.0 Trait
responses:
  500:
    description: Internal Error
    body:
      application/json:
        type: !include ../types/generic-error.raml
        example: |
          {
            "success": false,
            "correlationId": "fcf28d90-ccb6-11ea-9203-96b86d6f050e", 
            "errorCode": "1040",
            "errorMessage": "Invalid User"
          }
  