#%RAML 1.0 DataType

properties: 
  phAgentId?: string
  phProjectId?: string
  agentType: string
  firstName?: string
  lastName?: string
  email?: string
  phoneNumber?: string
  mobileNumber?: string
  faxNumber?: string
  username?: string
  level?: string
  description?: string
  position?: string
  suburb?: string
  role?: string 
  fullName?: string
