#%RAML 1.0 NamedExample
  unitCode: "P-001"
  agentFullName: "OwnerName"
  tenantType: "Individual"
  contactFirstName: "first"
  contactLastName: "LastName"
  contactEmail: "test@test.com"
  contactMobilePhone: "123344543"
  contactAddress1: "25th Ave"
  contactAddress2: "U-001"
  contactAddressState: "NY"
  contactZipcode: "12345"
  campaignSource: "campaign"
  projectPropertyCode: "0001"
  leaseStartDate: 2020-07-14
  leaseEndDate: 2020-08-13 
  SFOpportunityId: "00Q0iaixerdt23DDWS"
  SFContactId: "0030iaixerdt23DDWS"