#%RAML 1.0 DataType
description: address of the property

properties:
  unitNumber?: string
  streetNumber: string
  streetName: string
  suburb: string #it can serve city as well for other countries
  postcode: string     
  state: string 
  region?: string
  country: string
  latitude?: string
  longitude?: string
