https:
  port: "8082"
  host: "0.0.0.0"
  key:
    alias: "lendlease"

anypoint.api.id: "15979433"

sftp:
  host: "ftp.lendlease.com"
  port: "22"
  username: "sftpBtRTest"
  directory.path: "/upload/archive/unit_yexport"
  move.file.target.path: "/upload/archive/unit_yexport"

salesforce:
  username: "msapi@lendlease.com.imst"
  token.endpoint: "https://test.salesforce.com/services/oauth2/token"
  api.version: "47.0"
  consumer.key: "3MVG9e2mBbZnmM6kAwiWpvN5lAeZd.Wm.dzruEHCyV4d09QfiIr6.nek1MkCzBQ4n0BGSJPtkxa5eAMmfbDfN"
  consumer.secret: "218A6517F2520513577B3B74BD8621930F6323DA71B492D6FDE32618CADF1D03"
  password: "Mule$ofT2020"
  security.token: "pVV201BpNLYrko2bvS4Dz6niJ"  
  

json.logger.application:
  version: 1.0.0-SNAPSHOT
  name: sys-global-sfdc-api

globalOrg:
  listings.update.objectName: "PLM_ListingStatus__c"

validation.messages:
  product.id: "Invalid Product"

anypoint.mq:
  url: "https://mq-us-west-2.anypoint.mulesoft.com/api/v1"

unit.publish.q: "ll.yardi.unit.upsert.q"      
unit.availability.publish.q: "ll.unit.availability.update.q"    